### ISSUE TITLE
Failed to run on M1

### ISSUE THREAD

**Issue by oliverhihn** [th-koeln/mi-master-wtw#123]
Not sure if it actually is because of the Apple Silicone. Setting `platform: linux/amd64` in composefile did not help.
Error log:
```
Attaching to mi-master-wtw-webserver-1
mi-master-wtw-webserver-1  | ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
mi-master-wtw-webserver-1  | Configuration file: /srv/jekyll/_config.yml
mi-master-wtw-webserver-1  |             Source: /srv/jekyll
mi-master-wtw-webserver-1  |        Destination: /srv/jekyll/_site
mi-master-wtw-webserver-1  |  Incremental build: disabled. Enable with --incremental
mi-master-wtw-webserver-1  |       Generating...
mi-master-wtw-webserver-1  |                     done in 16.995 seconds.
mi-master-wtw-webserver-1  |  Auto-regeneration: enabled for '/srv/jekyll'
mi-master-wtw-webserver-1  |                     ------------------------------------------------
mi-master-wtw-webserver-1  |       Jekyll 4.2.2   Please append `--trace` to the `serve` command
mi-master-wtw-webserver-1  |                      for any additional information or backtrace.
mi-master-wtw-webserver-1  |                     ------------------------------------------------
mi-master-wtw-webserver-1  | <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- webrick (LoadError)
mi-master-wtw-webserver-1  | 	from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
mi-master-wtw-webserver-1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
mi-master-wtw-webserver-1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `require_relative'
mi-master-wtw-webserver-1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:179:in `setup'
mi-master-wtw-webserver-1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:100:in `process'
mi-master-wtw-webserver-1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
mi-master-wtw-webserver-1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
mi-master-wtw-webserver-1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
mi-master-wtw-webserver-1  | 	from /usr/gem/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
mi-master-wtw-webserver-1  | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
mi-master-wtw-webserver-1  | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
mi-master-wtw-webserver-1  | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
mi-master-wtw-webserver-1  | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
mi-master-wtw-webserver-1  | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
mi-master-wtw-webserver-1  | 	from /usr/gem/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
mi-master-wtw-webserver-1  | 	from /usr/gem/bin/jekyll:25:in `load'
mi-master-wtw-webserver-1  | 	from /usr/gem/bin/jekyll:25:in `<main>'
mi-master-wtw-webserver-1 exited with code 1
```

**Comment by oliverhihn** [comment]
Set fix version (4.2.0) for Jeykell did the trick. I made a [pull request](https://github.com/th-koeln/mi-master-wtw/pull/124).
